### ISSUE TITLE
News: 3 items are shown per paginated page, there are 112 paginated pages

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Standard-Website#185]
* PL shows one featured article and 3 other articles (total 4), staging only shows 1 featured 2 other

Are categories to be implemented?

https://iatistandard.org/en/news/

**Comment by allthatilk** [comment]
This one is for the IATI team to fix

**Comment by benjamincoleman** [comment]
Again, I don't think this is pattern library related. 

You should definitely increase the number of things shown per page here to 8/10 or so. 

As a future enhancement looking more featured pagination with group numbers would be good too
