### ISSUE TITLE
Cloudflare blocks requests with a user-agent containing “Python-urllib”

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-Website#230]
## How to test

```python
from urllib import request

url = 'http://iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml'
r = request.build_opener()
r.open(url)
```

## Expected behaviour

When I use urllib to visit http://iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml
, I expect the response to be a 301 redirect to http://reference.iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml

## Actual behaviour

When I use urllib to visit http://iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml
I get a 403 response.

## Why is this a problem?

URLs like http://iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml are supposed to be accessed programmatically, and previously succeeded. Now they break.

**Comment by akmiller01** [comment]
I have added a `Browser Integrity Check` bypass for files that might be a part of the Standard.

![image](https://user-images.githubusercontent.com/2836840/194126784-28e2963e-1714-4fab-a545-616cc412f448.png)

This should allow the example above to fetch the codelist without specifying a User-Agent:
```
>>> from urllib import request
>>> 
>>> url = 'http://iatistandard.org/203/codelists/downloads/clv1/codelist/IndicatorMeasure.xml'
>>> r = request.build_opener()
>>> r.open(url)
<http.client.HTTPResponse object at 0x7fd15c61f430>
```
