### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Standard-Website#268]
Following some internal chats we finally decided that `preview-website` should be replaced by `IATI-Standard-Website` as it's not a preview anymore.

We'll most likely get to it tomorrow/early next week, just raising this for now just in case anybody that wasn't involved in our internal discussion has anything to say against it / different suggestions

**Comment by samuele-mattiuzzo** [comment]
Everyone should update their references with

`git remote set-url origin git@github.com:IATI/IATI-Standard-Website.git`

**Comment by andylolz** [comment]
You might be on this already, but just in case: I think you have to update travis manually. Also, the travis badge in the README.

Just mentioning because I think this was an issue when the IATI-Datastore repo was renamed.

**Comment by samuele-mattiuzzo** [comment]
@andylolz yeah on it, just doing it one step at the time (currently trying to work out all the references to preview-website across our apps, apache confs and all that) 👍

**Comment by andylolz** [comment]
Cool!

**Comment by samuele-mattiuzzo** [comment]
Ah, fantastic, after syncing travis (new Standard-Website wasn't in the list), Travis dealt with it automatically (preview-website is gone, IATI-Standard-Website appeared)!

**Comment by andylolz** [comment]
Oh, nice!
