### ISSUE TITLE
"All the activity information you can publish" - page misses the Description element

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Standard-Website#290]
(I *think* this is the right repo to post this...)

Take a look at 
https://iatistandard.org/en/guidance/preparing-data/activity-information/activity-information-you-can-publish/

The table misses out the Description element

This element is actually required by the schema ( http://reference.iatistandard.org/203/activity-standard/summary-table/ ) - so the omission from this documentation is quite misleading

**Comment by akmiller01** [comment]
This one appears to be completed:

![image](https://user-images.githubusercontent.com/2836840/194129355-7ed050c2-8e77-464a-b375-546187c3634f.png)
