### ISSUE TITLE
Investigate how redirects are applied

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Standard-Website#296]
Several issues have arisen from the implementation of #295, meaning that we are becoming blocked and should take a step back to look at the wider picture.

Redirects are handled at server level, with various apache `.conf` files residing in [another repository](https://github.com/IATI/IATI-Websites/tree/master/iatistandard). Redirects are also handled by URL config and [a view](https://github.com/IATI/IATI-Standard-Website/blob/0904d0ca6d2db128b19ce014bda940082412ba35/iati/home/views.py#L6).

We have encountered some issues with this related directly to #295 - it is not clear which redirects are applied and when/why. Ideally, this should be consolidated, but due care needs to be taken to ensure that the new approach is robust and reliable, and importantly, readable. For now, let's understand all facets.

1. Investigate the `.conf` files and decipher which redirects are internal, and which are external. This information will be valuable for imminent deployment changes. 
2. Understand the `reference_redirect` view - what is the purpose of this, and what does it solve? How is it executed, in natural language terms? Is it still valuable, or is it defunct? Does this work alongside the apache redirects, and if so, how?
3. Are there any other ways that redirects are applied?

**Comment by Ocre42** [comment]
The `conf` files in the IATI-Websites repository contain redirects **to** `iatistandard.org` from either the reference site or the old aidtransparency site. 

`reference_redirect` takes any urls that start with the list in `REFERENCE_NAMESPACES` (from the [urls.py](https://github.com/IATI/IATI-Standard-Website/blob/master/iati/iati/urls.py) file) and just appends the slug at the end of `reference.iatistandard.org`

There's also wagtail redirects, which appear to just be redirects from broken slugs to their working versions: `/en/about/governance/governing-board-meeting-minutes-` (notice the - a the end)

**Comment by Ocre42** [comment]
As part of the work for this issue and #295 we've decided to rework the way we handle redirects:

1. Redirects to the reference site will be added manually to the Wagtail redirects.
2. `reference_redirect` will be removed from views and urls
3. Ensure that `WagtailRedirectMiddleware` is called before the custom middleware
4. Run tests to ensure it all works as intended.

**Comment by sargentfrancesca** [comment]
Fantastic! We will enforce adding redirects to Wagtail in the future. This means that development is not required to amend or add redirects.

**Comment by Ocre42** [comment]
Wagtail redirects won't work since they are meant for specific URLs and not for patterns (i,e: everything that starts with 203/202/201/etc to be redirected to the reference site would require an individual redirect to be added) We are readdressing this issue from a different approach.
