### ISSUE TITLE
Add a page to the menu item "community"

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Standard-Website#323]
Current behaviour:
In the top nav menu "community" is an option.  This takes a user directly through to discuss.iatistandard.org 

Desired behavour:
It would be good if we could have a page where we can add some sontent that talks about the IATI community and explains what discuss is, then the user can click through to discuss from this explaitory page.
Do you think we could try using one of our exisiting page templates? 

Ideally we'd have space for quite a bit of copy describing the community then some sort of box link to discuss.

Like the guidence parent page, except with space for editiable content before the box and link.  That is just a suggestion, totally happy with you doing something else if you have a better idea!

![Screenshot 2019-03-29 at 10 30 56](https://user-images.githubusercontent.com/36768381/55226904-077a8300-520e-11e9-8e80-4eddfce20d7a.png)

**Comment by k8hughes** [comment]
Is there a URL where I can see this?
I tried to play guess the URL:  https://iati-styles-staging.netlify.com/page-templates/community but I got it wrong.
I also tried clicking the word community, but that went straight through the discuss on the live site, so I am not sure how to review this issue.

**Comment by k8hughes** [comment]
@sargentfrancesca or @Ocre42 can this be reviewed?  If it can't be reviewed on staging we can always release it and test it on wagtail by previewing a new page additonal on the live site.

**Comment by sargentfrancesca** [comment]
@k8hughes ah yes, it can be reviewed on staging, but it needs adding first - we just will need to add a community page and make sure it works in the menu. If @Ocre42 can't address this today, I can do so first thing in the morning.
