### ISSUE TITLE
Add youtube icon linked to the IATI youtube account into the footer

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Standard-Website#324]
This is a link to our youtube account:  https://www.youtube.com/channel/UCAVH1gcgJXElsj8ENC-bDQQ 

Please can this be added to the footer.

Priority todo asap.

**Comment by k8hughes** [comment]
LGTM from UNDP.

Later this year we will have a linkedin account to add, but lets release this change and worry about the additional socal media when accounts are set up.

**Comment by sargentfrancesca** [comment]
@k8hughes that's fine, we can add a new issue for this when the LinkedIn account is ready
