### ISSUE TITLE
Add social share buttons to news content

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Standard-Website#325]
As a user, when I am on a new item I want to be able to share directly from the new item to facebook or twitter.

For example on this page:  https://iatistandard.org/en/news/syncing-iati-data-with-government-systems/ we'd want to have the social share icons at the top or to the side of the article.

Priority to do on a maintenance day.

**Comment by Ocre42** [comment]
Could we get a bit more depth as to what exactly we want for these? which social media sites? where would the buttons be placed?

**Comment by sargentfrancesca** [comment]
@k8hughes in case you didn't see ^

**Comment by sargentfrancesca** [comment]
Add to:
* [ ] News
* [ ] Events

We also need to check metadata in HTML for social media cards, and also if there is anything in the CMS promoted panel that needs to be bought through.

**Comment by sargentfrancesca** [comment]
Example of how social media buttons can be shown in pattern library: 

* https://iati-styles-staging.netlify.com/page-templates/03-1-news-single
* https://iati-styles-staging.netlify.com/page-templates/04-1-events-single

This might need to be changed, so will be pending review

**Comment by k8hughes** [comment]
I'm sorry I didn't see the questions where you asked for further details.  
UNDP have commented back that in addition to FB and Twitter they'd like to have the option to share on Linkedin.  Would it be possible to add this?  
The positioning of the buttons is good, just this one extra one to add.

**Comment by sargentfrancesca** [comment]
LinkedIn doesn't provide the same out-the-box share button that Facebook and Twitter do. In fact, they have updated their API to use OAuth - older versions of the documentation point towards the use of the url pattern:

```
https://www.linkedin.com/shareArticle?mini=true&url={URL}&title={TITLE}&summary={SUMMARY}&source=LinkedIn
```
[(example)](https://www.linkedin.com/shareArticle?mini=true&url=http://iatistandard.org&title=IATI%20Standard%20QWebsite&source=LinkedIn)

We can construct this into something, and find an image to use that is the same size and style as the others. Not as easy to implement as the other social media links, so it might not be a super quick fix.

**Comment by sargentfrancesca** [comment]
I stand corrected, @samuele-mattiuzzo found the correct [documentation](https://docs.microsoft.com/en-gb/linkedin/consumer/integrations/self-serve/plugins/share-plugin), and it works.
