### ISSUE TITLE
Add analytics tracking to annual report downloads

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Standard-Website#326]
We need to be able to tell how many times annual reports of each lanuage are being downloaded.  

https://iatistandard.org/en/about/governance/annual-reports/ 

Can we add the tracking params to 2018 (when launched, this is the first priority) then 2017 and 2016?  We can leave the older ones.

Priority for a maintenance day.

**Comment by samuele-mattiuzzo** [comment]
@sargentfrancesca I will pick this one up tomorrow, if you could update on the status movements (todo->cr->in progress) not matching the PR being merged that would be fab, so I know what to update the team with

Thanksse!!

**Comment by samuele-mattiuzzo** [comment]
Branch `326-adding-download-tracking` is now merged in `version-controlled-translations` and deployed to live 👍  Will now merge it in master as well, as it's a core functionality that doesn't need feature branches
