### ISSUE TITLE
Text overlaying boxes on resize when using google crome or firefox

### ISSUE THREAD

**Issue by k8hughes** [IATI/IATI-Standard-Website#327]
For example on this page: https://iatistandard.org/en/using-data/ 

On certain screen sizes the box at the bottom of the screen get messed up and the copy runs over behind the boxes. If the screen size doesn't allow for all the text to displayed in the box can it be cut off and have a ... instead of running under the button?

![Screenshot 2019-04-02 at 17 36 43](https://user-images.githubusercontent.com/36768381/55420021-f020fa00-556d-11e9-89e3-7792b78ff986.png)

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 @sargentfrancesca anyone working on this?

**Comment by samuele-mattiuzzo** [comment]
Work done in https://github.com/IATI/IATI-Pattern-Library/pull/106
Does not need any action on the website

**Comment by samuele-mattiuzzo** [comment]
This has changed a bit in implementation.

Will now provide a hidden by default pre-truncated second bit of text that will then be switched using the CSS rules defined in IATI/IATI-Pattern-Library#106

**Comment by samuele-mattiuzzo** [comment]
FYI: there's some templates for Knowledge Base that seem to be filled with `lorem ipsums` which I didn't touch
