### ISSUE TITLE
List all partners on home page

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Standard-Website#328]
The partners listed on the bottom of the home page should include all of our member organizations, not just two.

**Comment by samuele-mattiuzzo** [comment]
@sargentfrancesca @k8hughes do we have more context around this?

In the UNDP document there isn't much to go with to be honest

- for the list of partners and copy, I'll follow up with Rohini
- for the technical aspect: I suggest a horizontal sliding carousel, something akin to the slider option in here https://codepen.io/jh3y/pen/WwVKLN (bonus it's done in pure CSS so it's also quite cool)

listing them out alltogether won't work unless we resize the boxes

**Comment by k8hughes** [comment]
This has been briefed into Ben to offer a design solution.  For now it is blocked.

**Comment by akmiller01** [comment]
I don't think this issue is applicable to the current design of the home page. I don't see any partners on the home page. So presumably this has been solved by the Members Assembly page: https://iatistandard.org/en/governance/members-assembly/
