### ISSUE TITLE
BUG: Redirects to reference.iatistandard.org have their case altered

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-Website#332]
This is because the middleware that redirects to all lower case runs before the middleware that redirects to reference.iatistandard.org.

This affects any reference URLs in the wild that both a) point to iatistandard.org and b) include upper case. There are probably quite a few of these.

It’s better to fix this sooner rather than later, because this is a permanent redirect so it will get cached.

**Comment by andylolz** [comment]
I think there are a couple of problems with the tests and with `RedirectIATISites` that mean this bug isn’t picked up. I’ve sent a quick fix in #333, but it would be better to also fix the tests.

**Comment by samuele-mattiuzzo** [comment]
Interesting enough, some pdf documents get downloaded (https://iatistandard.org/documents/725/IATI_Annual_Report_2018.pdf) while some others are redirected to their lowercase (and non-existing) counterpart like this one https://iatistandard.org/documents/710/IATI_Tool_Guide_-_using_the_data.pdf

I have switched off both middlewares to test and this still seems to be the case (caching maybe?)

**Comment by andylolz** [comment]
I can’t tell if that’s because cloudflare’s cache needs purging, or because the document is missing, or something else.

**Comment by samuele-mattiuzzo** [comment]
one document was missing as we found out, so we'll re-upload that one (yay... ?)
I have cleared Apache's cache already, haven't touched Cloudflare yet, will also have to wait for Google to re-cache on their side as well I suspect
