### ISSUE TITLE
[Feature request] Anchors for headings

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Standard-Website#337]
### What is the feature?
Enable specific headings within content to be linked to directly. This was suggested in [this comment of the IATI Registry repository](https://github.com/IATI/ckanext-iati/issues/242#issuecomment-481712075). 

### Who does it benefit?
This benefits end users. Given the number of distributed tools of IATI and the vast documentation surrounding it, it would be beneficial to direct the user to the most relevant information available, especially in the case of a guidance page offering several sections of information.

### What problem does it solve?
This ensures information is flowing quickly, but mainly solves the problem of time and clarity.

### How do you see it in action?
One of two ways, depending on scoping:
1. **A Draftail extension that allows an ID to be added for a heading**. This requires some learning curve (for myself anyway), and I'm not quite clear of what the actual workflow would be for the user. Conceptually - would `H` elements be amended to add an extra step of adding an optional ID? Should an anchored element become available? Or should an agnostic element be created that could insert an ID into the HTML tag of whatever is in context of the element? **EDIT: [this extension](https://github.com/thibaudcolas/wagtail_draftail_experiments/tree/master/wagtail_draftail_anchors) could prove very useful.**
2. **A `StructBlock` for a `H2`** added to the content StreamField.  This would take the least time, is familiar, and an anchored header _does_ make sense as structured data. There could potentially be some CSS changes required for spacing, since we'd be breaking up rich text divs. Also will be more manual work for the editor when it comes to refactoring existing info.
There's more to think about on this, especially when considering the [suitability of whichever method is implemented](https://www.draftail.org/docs/getting-started-with-extensions#when-you-should-use-draftail). 

### Does it affect any other product?
No

### Any dependencies?
Depends on implementation

### Does it require community consultation?
No

### Risks? Draw backs? Assumptions? Caveats?
* In terms of implementation, these are covered above, but open to hearing more.

**Comment by samuele-mattiuzzo** [comment]
This is what makes me keen on picking `Draftail extension` over `StructBlock`

>     2\. There could potentially be some CSS changes required for spacing, since we'd be breaking up rich text divs. Also will be more manual work for the editor when it comes to refactoring existing info.

Ultimately we have to keep our editors and their work flow in mind, I think that's where the priority lives.

**Comment by sargentfrancesca** [comment]
Yeah, I can agree with that. It seems like a less evasive way to introduce this as a feature could be to add a Draftail extension as a new (optional) element. 

Let's scope with Draftail in mind.

**Comment by sargentfrancesca** [comment]
@samuele-mattiuzzo relevant thread: https://github.com/wagtail/wagtail/issues/1049

**Comment by akmiller01** [comment]
This functionality's available in our content-editor Anchor-point block: 

![image](https://user-images.githubusercontent.com/2836840/194132159-6c7a9e16-b08b-4376-a95b-36c09de82738.png)
