### ISSUE TITLE
Responsive CSS URI renders 404

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Standard-Website#357]
**Describe the bug**
CSS URI renders 404

**To Reproduce**
See: https://iatistandard.org/en/iatistandard.org/static/home/css/responsive.css

**Expected behavior**
Render 200

**Screenshots**

**Desktop (please complete the following information):**
mac, Chrome etc.

**Additional context**
Seems like serving old css locations.

**Comment by andylolz** [comment]
It’s due to a missing "https://" protocol here:

> href="iatistandard.org/static/home/css/responsive.css">

, similar to #347. Correct URL is:
https://iatistandard.org/static/home/css/responsive.css
