### ISSUE TITLE
Broken link on data quality page

### ISSUE THREAD

**Issue by rossjones** [IATI/IATI-Standard-Website#361]
**Describe the bug**

On http://reference.iatistandard.org/203/developer/data-quality/ there is a link to http://data.tickets.iatistandard.org/ which unfortunately doesn't exist.

**To Reproduce**

1. Visit http://reference.iatistandard.org/203/developer/data-quality/
2. Click http://data.tickets.iatistandard.org/
3. Be sad.

**Expected behavior**

To see a web page

**Screenshots**

<img width="642" alt="Screenshot 2019-07-19 at 11 03 09" src="https://user-images.githubusercontent.com/118063/61527649-db7d4a80-aa14-11e9-977a-477ba99fd87e.png">

**Comment by samuele-mattiuzzo** [comment]
This is one for the reference site https://github.com/IATI/IATI-Standard-SSOT/

Thanks for pointing it out!
