### ISSUE TITLE
Events are marked as past if start date is after today. Should be end date.

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Standard-Website#368]
**Describe the bug**
Looking for an event that is currently happening. It's hidden under "Past events". Should not be.

**To Reproduce**
1. Go to https://iatistandard.org/en/events/
2. Look for MA event (currently on)
3. View Past Events
4. Find the MA event

**Expected behavior**
Event still running should be on /events/ page

**Additional context**
We need to order by event end date and use `__gt`, not `__gte`

**Comment by andylolz** [comment]
I raised this in #195, but I think I concluded the fix wasn’t straightforward (see: https://github.com/IATI/IATI-Standard-Website/issues/195#issuecomment-403549975). Maybe that’s not relevant anymore – I don’t know. Just thought I’d flag.

**Comment by samuele-mattiuzzo** [comment]
for now it's just a hotfix, thanks for flagging anyway
