### ISSUE TITLE
T8.4 Tool

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#389]
Sketch - https://marvelapp.com/4cfjg52/screen/60422958

Design: http://iati.surge.sh/page-templates/08-4-tool

Original issues and comments: https://github.com/IATI/IATI-Pattern-Library/issues/116

**Hero**

* Logo of the tool, if available
* Title
* Intro
* Button to go to the external tool website

**Left nav**

Shows pages in this section. There are sub pages of tools that need to show when you are looking at the tool.

**Content**

* Content editor with captioned images
* Button repeated for the external tool link

**Comment by urlsangel** [comment]
@benjamincoleman 

Should the button label for the external URL be content-managed?

If not, should it be made up of "Go to " + (`url` - `http://`[`www`]) ?

![Screenshot 2019-12-16 at 14 51 27](https://user-images.githubusercontent.com/560463/70916609-e4019d80-2013-11ea-9c55-5d8f67a516f2.png)

**Comment by benjamincoleman** [comment]
Let's content manage it
