### ISSUE TITLE
Moving the reference - Standard Overview

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#397]
This content currently is wrapped up in the SSOT, you can see under each area there's "Overview" and "Elements" - http://reference.iatistandard.org/203/organisation-standard/. 

![Organisation Standard   The IATI Standard](https://user-images.githubusercontent.com/64877/70983778-38a72600-20b1-11ea-8e2e-f2a00e292842.png)

Whilst the "elements" stays in the SSOT driven content, we're taking the "Overview" content out and making it content managed by Wagtail. This will  be in the new "Guidance and Support" section as you can see in the IA below: 

![Screen Shot 2019-12-17 at 09 41 25](https://user-images.githubusercontent.com/64877/70983973-8c197400-20b1-11ea-80a5-ff568bc94fea.png)

I believe the content will be moved / edited and potentially rewritten by the IATI BA's @PetyaKangalova and Amy Silcock, however I'll ask for confirmation of that. I believe this means that a data migration will not be required, but if we can set up the structure for them to add content.

**Comment by benjamincoleman** [comment]
I've written this at the end of the issue and wanted to check whether I'm right or not:

> I believe the content will be moved / edited and potentially rewritten by the IATI BA's @PetyaKangalova and Amy Silcock, however I'll ask for confirmation of that. I believe this means that a data migration will not be required, but if we can set up the structure for them to add content.

**Comment by PetyaKangalova** [comment]
@benjamincoleman Yes, you are correct. The 'Overview' pages  under Activity and Organisation standard will be moved into Wagtail. Some are already re-written and the content can be moved straightaway, while other pages require consultation and will be moved later in the year. 

My view would be that for those pages that still require consultation and are not ready to be re-written, we just move them as they into Wagtail. Maybe we can update the IA by splitting which pages are ready and which still require consultation?

This is the correct place in the IA for the Overview Guidance pages:

![image](https://user-images.githubusercontent.com/24607542/71005115-00b4d880-20db-11ea-9596-ba171e34bf73.png)

From a dev perspective it is all on Wagtail.  Let me know if that is the answer you were looking for.

**Comment by PetyaKangalova** [comment]
@benjamincoleman just to confirm again that following our meeting with the team we all agreed to the "Overview" content out and making it content managed by Wagtail :)

**Comment by benjamincoleman** [comment]
@PetyaKangalova great, thanks. 

On this question:

> Maybe we can update the IA by splitting which pages are ready and which still require consultation?

I would say let's not - it would swiftly go out of date.
