### ISSUE TITLE
Moving the reference - Standard Guidance

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#398]
This is new content that has been / is being written by the IATI BA's Amy and Petya. 

This whole section sits in the new Guidance and Support section. 

You'll see that there is a v2 version of this that we'll go live with, but in the future there will be a v3 version of this which is almost a duplicate structure, so we'll need the ability to create a new one at some point. We should discuss whether it's more efficient to do that so that editors can create it, or if it's best to have developers clone that section. 

IA is here: 

![Screen Shot 2019-12-17 at 10 04 52](https://user-images.githubusercontent.com/64877/70985933-e2d47d00-20b4-11ea-8ce8-a0469c76b454.png)

It has a listing template, and a single template: 

**Listing** - http://iati.surge.sh/page-templates/02-9-standard-guidance

Sketch - https://marvelapp.com/4cfjg52/screen/62575949

Design issue - https://github.com/IATI/IATI-Pattern-Library/issues/128 so you can see the history.

This template shows all the guidance pages underneath ordered alphabetically

For each it shows: 

- title
- description / excerpt
- published date

The filter allows the user to filter the content according to two things: 

1. Taxonomy of what type of element / part of the standard it applies to. This is either `Organisation`, or `Activity`. 

2. The search box should autocomplete search against the titles of the guidance items. If you select an item there then it takes you to that page. If there's no JS then we could make it a standard Search box, or could not show it? Let me know what you think @urlsangel. 

**Single** - http://iati.surge.sh/page-templates/06-1-guidance-page

Fairly simple template, you can see the issue for the design here: https://github.com/IATI/IATI-Pattern-Library/issues/141

It has a feature on the right, which allows you to select related guidance pages from this same section.

**Comment by benjamincoleman** [comment]
@PetyaKangalova Do you have an opinion on whether it would be better for us to allow you to create new Standard Guidance versions of this via Wagtail, or would you rather have a developer clone the v2 to make v3?

**Comment by PetyaKangalova** [comment]
@benjamincoleman to give you a bit of context. The v3 guidance is something that will hopefully happen in the near future, but it requires a formal upgrade process of the IATI  standard first. What this means is we would not have only one additional guidance page for v3, but will have to rewrite and update all pages following a v3 upgrade process.

So my logic then is that the better option is to have a developer clone the v2 to make v3 and then in the  future when we upgrade to v3 and have updated our guidance pages (in consultation with the IATI community), we just amend the content in Wagtail. Is there any other benefit to being able to create new versions via Wagtail?

**Comment by benjamincoleman** [comment]
@PetyaKangalova 

> Is there any other benefit to being able to create new versions via Wagtail?

The only benefit is that you would not need a developer to clone it. Thanks :)
