### ISSUE TITLE
Restructuring the Publishing Guidance

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#399]
So this piece is a bit of a migration or re-structuring of pages. 

At the moment we have the publishing guidance split into 3 sections as you can see here: https://iatistandard.org/en/guidance/

1. Preparing your organisation
2. Preparing your data
3. Publishing your data

We've re-worked that structure and so the pages need to move around. Oh for a Wordpress drag and drop view eh?

So, the new structure is shown in the IA snapshot below: 

![Screen Shot 2019-12-17 at 09 35 15](https://user-images.githubusercontent.com/64877/70983400-9129f380-20b0-11ea-91fb-ed187d80dcdd.png)

As there are only a certain number of pages, this might not need a migration script persay, but we should discuss that. 

One key thing is that this is now part of the new Guidance and Support section, so might be good to check the whole IA doc for that.

**Comment by benjamincoleman** [comment]
@PetyaKangalova can you review what I've written above please?

**Comment by PetyaKangalova** [comment]
@benjamincoleman , what you have written above looks right! It is mainly re-structuring the pages as per the latest IA.

On the IA side, I cannot recall what the last discussion was when we talked about this circular diagram- do you remember? Did we agree to just split the sub-pages as there was no way in visually representing the publication process in a circular way?

![image](https://user-images.githubusercontent.com/24607542/71009513-44f7a700-20e2-11ea-9b5e-b652b20ee1d2.png)

**Comment by benjamincoleman** [comment]
@PetyaKangalova 

> On the IA side, I cannot recall what the last discussion was when we talked about this circular diagram- do you remember? Did we agree to just split the sub-pages as there was no way in visually representing the publication process in a circular way?

Essentially yes, the IA above shows process left to right.
