### ISSUE TITLE
Case studies page

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#402]
Can we investigate the cause of this bug? 

https://iatistandard.org/en/about/case-studies/

**Comment by BenDarby** [comment]
@benjamincoleman it's because of the issue with basic.css the other week. It looks like it has only been applied to this page for some reason, not sure how though. Needs removing

**Comment by benjamincoleman** [comment]
@urlsangel I thought we had sorted this issue?
