### ISSUE TITLE
Translated menu search box needs to adapt

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#407]
Currently seems to be a fixed width, which obviously wont work with translations as you can see below.

<img width="171" alt="Screen Shot 2020-01-08 at 09 41 43" src="https://user-images.githubusercontent.com/64877/71967444-44db5a80-31fb-11ea-91c6-339bc48f4fab.png">

Can be seen here: https://dev.iatistandard.org/fr/

Related to #408

**Comment by BenDarby** [comment]
@benjamincoleman it's not a fixed width, just separate elements positioned. I'll just need to rework section
