### ISSUE TITLE
Secondary menu missing on mobile menu

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#412]
News, Events and Contact are all missing, they should appear after the primary menu list. 

Also, any way we can have the primary menu first, then the search, language.

**Comment by BenDarby** [comment]
@benjamincoleman @urlsangel the secondary menu is there, it looks like the `has-children` class is getting applied to these and that's the only thing I can think of that is causing this. Ideally we don't need that class added when on mobile, I think it's added with JS as it's not in the html?

**Comment by BenDarby** [comment]
@benjamincoleman @urlsangel the secondary nav is there, it's just not showing when going from desktop to mobile. It looks like the `mega-menu` classes and attributes are being added to these as well which is causing them to disappear. @urlsangel is there a way we have it so any primary nav item with the class `navigation-primary__item--ss-only` doesn't have the mega nav added

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

The current implementation only adds the accessible meganav on large screens, but it’s already done its business if you then shrink to mobile. I guess this is still an edge case problem, e.g. if you switch rotation on a tablet and it goes from desktop to mobile style nav, so I'll implement a fix.
