### ISSUE TITLE
Convert Search view to be a Wagtail page

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#422]
The current search template is a Django view, and therefore sites outside Wagtails control. The downside of that is that Wagtail doesn't know about it, and it's not translatable. It should be converted to be a Wagtail page.

**Comment by urlsangel** [comment]
@benjamincoleman 

This is done and on the `dev` server for review:

https://dev.iatistandard.org/en/search/?query=water

### Public page filtering

**Note:** page search is filtering by `public()`, so results will be empty if the site home page is set to `private` (as on `dev` or `staging`). Unset this setting temporarily to test the page.

### Search request downtime on deployment

This branch upgrades Elasticsearch from `2.3.5` to `6.4.0` - this process will require destroying and recreating the attached ES container for `staging` and `www` servers at deployment time. 

This will cause search page request to return `500` errors to individual users whilst this process takes place (about 5 minutes). Recommend deploying first thing UK time to avoid peak traffic hours.

### Translation

This branch contains an uodated `.po` file for the static text to be translated to French. Need to liaise with Alex to confirm they are correct, and then send them for translation before integrating into the branch pre-deployment.

### Deployment notes

When deploying, follow these steps:

`ssh` to server

#### Staging deployment:
- run: `export ELASTICSEARCH_IMAGE_VERSION="6.4.0"`
- run: `dokku elasticsearch:unlink staging staging`
- run: `dokku elasticsearch:destroy staging`
- run: `dokku elasticsearch:create staging`
- run: `dokku elasticsearch:link staging staging`
- local push: `git push staging master:master`

#### WWW deployment:
- run: `export ELASTICSEARCH_IMAGE_VERSION="6.4.0"`
- run: `dokku elasticsearch:unlink www www`
- run: `dokku elasticsearch:destroy www`
- run: `dokku elasticsearch:create www`
- run: `dokku elasticsearch:link www`
- local push: `git push www master:master`
