### ISSUE TITLE
T10 - Get involved (was Membership / Community)

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#426]
This was a new "community and membership" section, then UNDP requested it be renamed "Get involved". 

For the top level page:

* Sketch: https://marvelapp.com/4cfjg52/screen/61443824
* Design: http://iati.surge.sh/page-templates/10-get-involved
* History is on this issue: https://github.com/IATI/IATI-Pattern-Library/issues/126

**Comment by benjamincoleman** [comment]
@BenDarby there's an update to this template - notice the two blocks at the bottom that talk about code of conduct and get involved. 

I've updated them to all be in these grey boxes - they are all sub pages of this page after all

**Comment by BenDarby** [comment]
@benjamincoleman I added a no image variation of the CTA boxes at the bottom http://iati.surge.sh/page-templates/10-get-involved
