### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#427]
We have a new design for the homepage to add: 

http://iati.surge.sh/page-templates/0-home

And it has an optional video in the hero: 

http://iati.surge.sh/page-templates/0b-home-video

History for the design to date is on this issue - https://github.com/IATI/IATI-Pattern-Library/issues/122

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

The date format on the latest news module on the home page doesn't match the format on the news listing page, and the examples also have no year (should the year only not show if the news was from this year?).

I'm going to implement the date format from the listing page, as I think it's messy to have inconsistent formats around the site - please advise if you'd like it formatted as per the PL (and what to do about the year in this case).

http://iati.surge.sh/page-templates/0-home
![Screenshot 2020-02-21 at 11 44 16](https://user-images.githubusercontent.com/560463/75032181-d519ea00-549f-11ea-862b-0b16c7b1efa8.png)

https://iatistandard.org/en/news/
![Screenshot 2020-02-21 at 11 44 27](https://user-images.githubusercontent.com/560463/75032182-d5b28080-549f-11ea-8897-2f8964f0ecf6.png)

**Comment by benjamincoleman** [comment]
@urlsangel good call - we should maintain the standard date formatting please

**Comment by benjamincoleman** [comment]
@urlsangel @BenDarby if we have the video option live then we'd likely not show the About IATI section later on. 

http://iati.surge.sh/page-templates/0b-home-video

Can you abstract / check what to do with the background colouring if that module is not present? I'm not sure whether its best to do that in development?

**Comment by urlsangel** [comment]
@BenDarby 

If some modules are now optional, then the home page modules will need refactoring so that they can be fed class modifiers based on how they are displayed/ordered on the page such as `--white` and `--grey`.

Be good if you could mock this up in the PL?

**Comment by benjamincoleman** [comment]
@BenDarby On the homepage variant with the video in the hero, http://iati.surge.sh/page-templates/0b-home-video, can you remove the video from the About IATI section and make the text work in two columns, please?

The About IATI module with the video needs to stay the same for the normal homepage template:  http://iati.surge.sh/page-templates/0-home

**Comment by BenDarby** [comment]
@benjamincoleman I've updated the homepage video template to make the about section 2 columns. There is a slight change to the markup now for this section, the `2up` classes can now be removed and we can add the `is-typeset--columns` modifier class to the text container div. Example: 
```
<div class="row">
        <div class="section-alt-top section-alt-bottom">
            <h2 class="section__heading">About IATI</h2>
            <div class="is-typeset is-typeset--article is-typeset--columns">
                <p>Duis sit amet aliquam enim. Donec tempus nisi est, vel finibus dolor finibus sit amet. Pellentesque maximus sollicitudin urna.</p>
                <p>Nulla in nunc at ipsum tincidunt convallis. Duis sit amet aliquam enim. Donec tempus nisi est, vel finibus dolor finibus sit amet. Pellentesque maximus sollicitudin urna.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <a class="button" href="#none">Find out more about IATI</a>
        </div>
    </div>
```
