### ISSUE TITLE
Governance - member's assembly

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#429]
The list of members has been redesigned: https://github.com/IATI/IATI-Pattern-Library/issues/123

**Comment by urlsangel** [comment]
This is now on the dev server for review:

https://dev.iatistandard.org/en/about/governance/members-assembly/
https://dev.iatistandard.org/cms/pages/662/edit/

This page uses the standard content editor for the intro above the chairs section, and has repeating inline panels to add a chair (max number of one) and vice-chairs (no max number).

### Members
Member objects are a snippet, and are able to be imported via a CSV - the dev data set was imported from this data (which was copied from the live site HTML): https://docs.google.com/spreadsheets/d/1JwskzEmg4Y_p6nSECs3Vj7bm-z3N-IjkXfJzUgnBa9k/edit?usp=drive_web&ouid=104128820495773707108

There are currently no image objects created on the data import, but this could be added if desired - we would need to assign ids or structured names to the image files to link the newly created objects.

Member objects have an `active` field set to `True` by default - this allows members to be hidden but their data kept if needs be.

https://dev.iatistandard.org/cms/snippets/governance/member/

### Constituencies
The filters are based on the constituency fields imported with the Member data, so if new rows are added to the data import set their labels need to be identical to prevent creation of incorrect duplicates.

https://dev.iatistandard.org/cms/snippets/taxonomies/constituency/

The filtering and ordering has been implemented to work in all languages, whether translated slugs are used or the default `en` slugs of the constituencies.

**Comment by benjamincoleman** [comment]
@urlsangel I believe we have a set of logos to use for the members assembly import. 

https://www.dropbox.com/sh/v6zw1p48clt1t90/AADI5KNq6cH25EEczJdntm9sa?dl=0

They have also been added to the spreadsheet: https://docs.google.com/spreadsheets/d/1JwskzEmg4Y_p6nSECs3Vj7bm-z3N-IjkXfJzUgnBa9k/edit#gid=0

Any updates or new ones required, Jonti can help.
