### ISSUE TITLE
Image captions text is huge

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#458]
Image caption text is coming out very large: 

Preview this page - https://iatistandard.org/cms/pages/668/edit/#tab-english to see this. 

![Screenshot 2020-03-19 at 10 02 37](https://user-images.githubusercontent.com/64877/77055527-f4396800-69c8-11ea-95ad-3bba27386635.png)

Markup around the image: 

```
<figure class="media-figure media-figure">
    <img src="/media/images/Dashboard_-_duplicate_identifiers_ZBzW4AC.max-1280x1280.png" width="626" height="276" alt="Dashboard - duplicate identifiers.PNG">
    <figcaption class="media-figure__caption">
        <div class="rich-text"><p>Organisations with duplicated identifiers</p></div>
    </figcaption>
</figure>
```

**Comment by BenDarby** [comment]
@benjamincoleman the markup differs from the pattern library, there is no `<div class="rich-text">` or `<p>` inside the `<figcaption>` this seems to be what's causing the issue. I can amend the CSS so adding `<p>` won't affect the size but afaik these tags aren't needed in inside a `<figcaption>`

PL markup is: 
```
<figure class="media-figure media-figure--alignright">
	<img src="/assets/img/ptn-example.jpg" alt="Inline image">
	<figcaption class="media-figure__caption">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.</figcaption>
</figure>
```

**Comment by benjamincoleman** [comment]
@urlsangel see @BenDarby's comment - the large captions are due to some extra markup being used in the live site - is this something that can be corrected there, or do we need a CSS solution?

**Comment by urlsangel** [comment]
@benjamincoleman 

I'm guessing this has always been like this since the site was built (I don't think I've introduced this behaviour).

I'll figure it out locally here and then advise on the best course of action.

**Comment by benjamincoleman** [comment]
Thanks

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Okay, after doing some digging I've noticed that there is at least one dependency within a Django management command for translations that relies on this HTML structure.

https://github.com/IATI/IATI-Standard-Website/blob/master/modeltranslation_sync/management/commands/fix_trans.py#L95

For this reason, I'd say the safest solution would be to amend the CSS rather than the generated markup, as this is less likely to cause unforeseen side effects than changing the currently rendered HTML.

**Comment by BenDarby** [comment]
@urlsangel I pushed a fix for this so `<p>` inside the `<figcaption>` will output the correct font size. It's in a feature branch called `image_caption `

**Comment by urlsangel** [comment]
Cheers @BenDarby :-)
