### ISSUE TITLE
Meganav infobox size

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#480]
Issue: On the dropdown for Guidance and support we have one wide infobox, and then 4 columns with a link box in each column. The tab has resulted in a quite compressed design, which I want to improve

![Screenshot 2020-04-16 at 15 38 04](https://user-images.githubusercontent.com/64877/79469598-48e7f700-7ff8-11ea-83e6-d153de786d83.png)

Solution: Allow the infobox to be the smaller variety, giving the columns on the right more space. We’ll do this with an option in the editor - Wide or Narrow.

**Comment by urlsangel** [comment]
@benjamincoleman 

This is on `dev` for review:

- https://dev.iatistandard.org/en/

I've set the `regular`/`wide` highlight on each pillar of the nav - can you check and confirm that you're happy with these?

**Comment by benjamincoleman** [comment]
@urlsangel yes this is looking good!
