### ISSUE TITLE
z-index menu bug

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#482]
z-index bug which you can see on the dev site where the red box appears over the menu dropdowns. 

![Screenshot 2020-04-16 at 15 43 02](https://user-images.githubusercontent.com/64877/79470164-fe1aaf00-7ff8-11ea-8e3f-7602b98d2dac.png)

**Comment by BenDarby** [comment]
@benjamincoleman I updated the z-index to fix this issue and updated surge so you can see http://iati.surge.sh/page-templates/ these fixes are in a feature branch called `meganav_amends`

**Comment by benjamincoleman** [comment]
@urlsangel think this is good to go when we've the rest of the amends complete on this feature branch
