### ISSUE TITLE
Page message

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#484]
https://iatistandard.org/ currently has a message below the hero about Covid19. 

<img width="303" alt="Screenshot 2020-04-16 at 16 14 23" src="https://user-images.githubusercontent.com/64877/79473658-5bb0fa80-7ffd-11ea-9970-7bbbae18e0c3.png">

We'd like to improve this and make it work better. For example, there's issues around having multiple `<p>` tags in it when a message is longer. The measure is too long. The wrapping around the icon isn't great etc.

**Comment by BenDarby** [comment]
@benjamincoleman I've updated how the `hero-notice` module looks to address the wrapping and measure issues, this is how it looks now
<img width="1489" alt="Screenshot 2020-04-21 at 11 36 10" src="https://user-images.githubusercontent.com/944594/79857418-ab107580-83c5-11ea-80fb-68e5dcfe4f5c.png">

I've pushed to the `notification_message` feature branch

**Comment by benjamincoleman** [comment]
@BenDarby can you update to check that this allows multiple `<p>` tags -  that was missed in my original message as I forgot to put the check marks around it to show the code, sorry

**Comment by BenDarby** [comment]
@benjamincoleman ah sorry, made the small amend to allow for multiple `<p>` which can be seen here: 
<img width="1556" alt="Screenshot 2020-04-22 at 12 32 53" src="https://user-images.githubusercontent.com/944594/79976972-6ce28700-8495-11ea-99f7-27de015416ae.png">

**Comment by urlsangel** [comment]
**PageNotice**

```
display_type: options: all pages, selected page only, selected page and all child pages, children of selected page
message_type: options: warning (red), alert (yellow), notice (green)
allow_dismiss: checkbox, default false, help_text:'Select to allow visitors to dismiss this message for two weeks'
content: rich text, h2, p, link, bold
```

A snippet type that allows multiple messages to be created for different use scenarios.

Pages that have more than one notice available will display the most specific, e.g. a `selected page` notice will take precedence over an `all pages` notice. If more than one exists with the same specificity, the latest (highest id) will be displayed.

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Chrome/Mac: the date on the news page template overlays the message bar, which may obscure a longer message.:

![Screenshot 2020-04-28 at 15 12 47](https://user-images.githubusercontent.com/560463/80498163-4f189480-8963-11ea-9f55-9487cbf3f057.png)

**Comment by BenDarby** [comment]
@urlsangel there is a body class of `body--news-single` applied to this template so I altered the max-width of the notice content so it doesn't interfere with the News meta

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman

This is done and on dev for review:

- https://dev.iatistandard.org/
- https://dev.iatistandard.org/cms/notices/pagenotice/

If you review the edit screen above, you can see which page notices apply in different parts of the site, and how dismissing one will allow the next specific notice to be shown on refreshing the page (if applicable).
