### ISSUE TITLE
Global site message

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#485]
We'd like to include a global message above the site header for announcements. A bit like #484.

**Comment by BenDarby** [comment]
@benjamincoleman Would this one be more like the one we did for Brunelcare? So the user can close the message announcement. Also, I presume we should style it differently to the homepage message

**Comment by benjamincoleman** [comment]
@BenDarby yes please

**Comment by BenDarby** [comment]
@benjamincoleman How is something like this? I decided to use the light blue as it has high contrast against other elements on the page so it stands out more. 
<img width="1384" alt="Screenshot 2020-04-22 at 14 59 42" src="https://user-images.githubusercontent.com/944594/79991284-07e55c00-84aa-11ea-85b5-c9bd8889836d.png">

**Comment by urlsangel** [comment]
@benjamincoleman 

Here's my thoughts on a model that will work for the global message and homepage message:

**SiteMessage**

```
display_type: options: global, selected page only, selected page and child pages
display_position: options: above hero, below hero
message_type: options: error (red), warning (yellow), notice (blue)
allow_dismiss: checkbox, default false, help_text:'Select to allow visitors to dismiss this message for two weeks'
content: rich text, h2, p, link, bold
```

A snippet type that allows multiple messages to be created for different use scenarios.

On save, the snippet should check that are no existing messages that conflict with the chosen settings - e.g. only one message can exist that is global and above hero, one per selected page etc. In such cases, saving of the new message will be disallowed and advice displayed to either change the new message settings or remove the conflicting existing message.

**Comment by urlsangel** [comment]
**GlobalNotice**

```
notice_type: options: error (red), warning (yellow), notice (blue)
content: rich text, h2, p, link, bold
```

A snippet type that allows a single global messages to be created for global site display.

On save, the snippet should check that are no existing global messages, and the admin 'add' button should not be displayed if an existing global message exists.

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Chrome/Mac: global site message obscures the search overlay:

![Screenshot 2020-04-28 at 15 14 04](https://user-images.githubusercontent.com/560463/80498311-7a02e880-8963-11ea-9f04-c412c658baec.png)

**Comment by BenDarby** [comment]
@urlsangel I increased the z-index of the header search so it appears above the global message :)

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

This is done and on `dev` for review:

- https://dev.iatistandard.org/
- https://dev.iatistandard.org/cms/notices/globalnotice/
