### ISSUE TITLE
SSOT code/pre blocks and syntax highlighting

### ISSUE THREAD

**Issue by urlsangel** [IATI/IATI-Standard-Website#489]
Syntax highlighting has now been implemented in the PL as a new JS app that can be used by Wagtail: `app-reference.bundle` - this is using the latest version of `highlight-js`.

The markup elements in the actual SSOT are back to front - `highlight-js` is looking for `<pre><code>`, but the actual content is structured as `<code><pre>`.

I’ve added a custom JS call to fix this, but it does mean that the styles on the actual content are different to the PL, as the background on the `hljs` class is now on the inner container rather than the outer container.

Compare these pages to see what i mean:

- http://iati.surge.sh/page-templates/09-1-reference
![Screenshot 2020-04-23 at 10 35 36](https://user-images.githubusercontent.com/560463/80084045-43396680-854e-11ea-8f59-5a61d642248f.png)

- https://dev.iatistandard.org/en/iati-standard/guidance/guidance/activity-thematic-focus/
![Screenshot 2020-04-23 at 10 35 44](https://user-images.githubusercontent.com/560463/80084063-4896b100-854e-11ea-824b-c5afd58010a7.png)

Here’s a PL template with actual SSOT content, again the grey background should be on the outer element:

- http://iati.surge.sh/page-templates/09-1d-example-content
![Screenshot 2020-04-23 at 10 36 00](https://user-images.githubusercontent.com/560463/80084083-4fbdbf00-854e-11ea-9c84-1a0637ff8b62.png)

**Comment by BenDarby** [comment]
@urlsangel @benjamincoleman we can style it okay, I amended the `_highlgiht-js.scss` to change the background color and it looks okay to me. http://iati.surge.sh/page-templates/09-1d-example-content so you can double-check too
