### ISSUE TITLE
T6.1 Guidance Single Page

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#504]
Design: http://iati.surge.sh/page-templates/06-1-guidance-page

Shows an individual guidance page. 

@BenDarby need to add: 

1. A sub title to the page to contain the Last Updated date, and a link to 'view changes'. 

2. A breadcrumb as follows: `Guidance & Support > Standard Guidance v2 > Activity Budgets`

**Development notes**

In the hero we have: 

- Page title
- Last updated date
- Link to view last changes to this RST file in Github

Underneath the hero we have: 

- Breadcrumb
- Page content
- Related guidance - this would come from a scrape of links included in the RST content that are also guidance pages.

**Comment by BenDarby** [comment]
@benjamincoleman I have added a breadcrumb module to this template and added a sub-title/notice to show to was last updated, we have used the notice style in other places for similar things so I thought it would be best to use it here as well. You can see it here: http://iati.surge.sh/page-templates/06-1-guidance-page

**Comment by benjamincoleman** [comment]
@BenDarby some updates: 

The last updated and "view changes" link shouldn't be as a notice - that'll get conflated with the notices we've just added. Can you add it in the hero under the title please? Stylewise it's not a notice, it's data about this piece of information. The user need is: "I need to see when this content was last edited, and be able to see the changes made". So we have date, and a link to the changes. 

Can we add a 3rd item to the breadcrumb with no link to represent the current page and use the names of the pages as indicated in the issue?

**Comment by BenDarby** [comment]
@benjamincoleman Ah okay that makes sense, we have a sub-title style already too so I have updated the template http://iati.surge.sh/page-templates/06-1-guidance-page

**Comment by benjamincoleman** [comment]
@BenDarby that's great
