### ISSUE TITLE
T2.9 Guidance Listing

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Standard-Website#505]
http://iati.surge.sh/page-templates/02-9-standard-guidance

Shows a list of guidance articles - no pagination, just show all of them in alphabetical order. 

User can filter by Organisation / Activity using the checkboxes

User can filter by search box

For each guidance page box: 

- Title
- Last updated date
- Excerpt - 1st XX characters of content

**Comment by akmiller01** [comment]
Will there be pagination on the index page?

**Comment by benjamincoleman** [comment]
Nope, no pagination - we want them all there on one page.
