### ISSUE TITLE
Various reference URLs are no longer redirecting

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-Website#558]
URLs of the form:
https://iatistandard.org/en/iati-standard/activity-standard/iati-activities/iati-activity/related-activity/

Previously redirected to the latest version of the standard, i.e.:
https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/related-activity/

It looks like that has broken recently, possibly related to #531.

**Comment by akmiller01** [comment]
Thanks, Andy.

I don't believe the redirection behavior has changed as a result of the new stack.

We still have one domain continuing to point at the previous server, and you can see the behavior is the same for the URL example you gave: https://staging.iatistandard.org/en/iati-standard/activity-standard/iati-activities/iati-activity/related-activity/

The redirections were designed to redirect from the previous reference.iatistandard URLs to the new format, and thus they never had `en/iati-standard` at the beginning.

If you take a URL in the format reference.iatistandard used to use, you can see it redirects to the latest version properly: https://iatistandard.org/activity-standard/iati-activities/iati-activity/related-activity/

**Comment by andylolz** [comment]
Wow, speedy response. Thanks @akmiller01.

I probably shouldn’t have sounded so sure about this! I’m in fact not at all sure – I just noticed several broken links, and suspected the stack change might be the cause.

I’m specifically looking at the [proposed traceability guidelines](https://docs.google.com/document/d/1bogQHZ9fQCa37xQSw5K3JTvIvKW1GTyJwkwDbdmgnSs/edit), and noticed several of the links are broken. Google Drive successfully shows a preview, though (see screenshot below), suggesting that they previously worked.
![Screenshot 2021-05-20 at 13 52 47](https://user-images.githubusercontent.com/464193/118981818-acb6bf00-b972-11eb-9021-5f04af93ce50.png)
