### ISSUE TITLE
Links to all documents are broken

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Standard-Website#618]
**Describe the bug**
Attempting to access any (?) document on iatistandard.org leads to an Error 421.

**To Reproduce**
1. Go to [Spotlight on IATI Data Use](https://iatistandard.org/en/using-data/iati_data_use_research/)
2. Click on any document
3. See the error in plaintext `<h2>Our services aren't available right now</h2>`...
4. Go to [IATI Strategic Plan](https://iatistandard.org/en/governance/iati-strategic-plan-2020-2025/)
5. Click on any document
6. See the error in plaintext `<h2>Our services aren't available right now</h2>`...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 99.0

Also, all documents redirect from e.g.:
https://iatistandard.org/documents/760/IATI_Strategic_Plan_2020_-_2025.pdf
to:
https://prod-iati-website.azureedge.net/prod-iati-website/documents/IATI_Strategic_Plan_FR_2020-2025.pdf

**Comment by akmiller01** [comment]
Hi @markbrough, I'm unable to recreate the issue. Could you let me know if it's still happening for you? If not, our CDN might have experienced a temporary outage. If so, the CDN servers that serve your region may be down, and I could look into that.

**Comment by markbrough** [comment]
Looks like it's working again -- thanks for the quick response, @akmiller01!

**Comment by akmiller01** [comment]
It turns out our CDN was down temporarily. Just got this notification from Azure:

```
Summary of Impact: Between 17:54 UTC and 18:50 UTC on 30 Mar 2022, you were identified as a customer using Azure Front Door who may have experienced 421 errors for subset of requests.

Preliminary Root Cause: We determined that there was a bad configuration with a recent deployment that caused the issues above.

Mitigation: We rolled back this deployment to mitigate the issue.

Next steps: We will continue to investigate to establish the full root cause and prevent future occurrences. We deeply apologize for this incident and for any inconvenience this may have caused.
```
