### ISSUE TITLE
Accessing the Using IATI data( UsingDataPage - page-type) page in the wagtail CMS produces a 500 error

### ISSUE THREAD

**Issue by ThatcherK** [IATI/IATI-Standard-Website#691]
**Describe the bug**
Any attempt to try to access the child pages of this page gives a 500

**To Reproduce**
1. Go to the home page in the CMS
2. Click on the arrow button that should show the child pages of the Using IATI data page
3. See error

**Expected behavior**
The child pages should be shown without errors

**Screenshots**
<img width="1433" alt="Screenshot 2023-01-31 at 15 09 30" src="https://user-images.githubusercontent.com/32189973/215781414-67138c2f-4430-48b6-ab77-91753fa400de.png">

**Comment by akmiller01** [comment]
@ThatcherK turns out they removed the `ToolsIndexPage` and `ToolsPage` models (to move them to a dedicated `tool` module), but only migrated the pages over, and then unpublished the pages for which the models were erased. So these weren't live pages anyway, and I was just able to erase them to solve the problem:
```
>>> from wagtail.core.models import Page
>>> trouble_ids = [550,551,552,553,554,555,556]
>>> trouble_pages = Page.objects.filter(id__in=trouble_ids)
>>> for trouble_page in trouble_pages:
...     print((trouble_page.specific, trouble_page.live))
... 
(<Page: Tools and resources for data use>, False)
(<Page: Using the IATI Registry>, False)
(<Page: Using the IATI Datastore>, False)
(<Page: Using d-portal>, False)
(<Page: AIMS - Aid Information Management Systems>, False)
(<Page: Using the CSV Query Builder>, False)
(<Page: Third-party tools and services for data use>, False)
>>> parent_trouble = Page.objects.get(id=550)
>>> parent_trouble.delete()
```
