### ISSUE TITLE
Broken link in 'How IATI works'

### ISSUE THREAD

**Issue by odscrachel** [IATI/IATI-Standard-Website#733]
**Describe the bug**
A user has highlighted that there is a broken link on the following page https://iatistandard.org/en/about/iati-process/ 

> 
> "At the heart of our work is the [IATI Standard](http://alpha.iatistandard.org/en/about/iati-standard/). This is a set of rules and guidance > produced by IATI for publishing useful development and humanitarian data."

I'm guessing this should just link to https://iatistandard.org/en/about/iati-standard/

**Comment by Bjwebb** [comment]
I've update this in the cms admin interface.
