### ISSUE TITLE
alpha.iatistandard.org no longer exists

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-Website#734]
We link to alpha.iatistandard.org in a few places on the website. Ideally these should be updated to iatistandard.org, but we can also put a redirect in place.

@IsabelBirds Can you remember the example you found. Does a redirect sound good to you?

**Comment by IsabelBirds** [comment]
Sorry @Bjwebb I really unhelpfully haven't noted this anywhere. A redirect sounds sensible.
