### ISSUE TITLE
Sharing a link from the site does not include a preview type image

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Standard-Website#747]
Sharing this link in an application such as Mattermost:

https://iatistandard.org/en/news/tag-piccolo-a-minitag-in-rome/

results in:

![Screenshot from 2024-03-20 17-33-23](https://github.com/IATI/IATI-Standard-Website/assets/1209944/3a7b4408-54a0-49c7-aa6e-27fcd13bbfec)

I don't know what the preview image should be, but it should be something?

**Comment by Bjwebb** [comment]
Looks like we've just got a double https:// for some reason:

```
<meta property="og:image" content="https://https://cdn.iatistandard.org/prod-iati-website/img/iati-share-social.png">
```

Looks like if will default to just the IATI logo, but that would be an improvement on broken: https://cdn.iatistandard.org/prod-iati-website/img/iati-share-social.png

**Comment by stevieflow** [comment]
Nice - thanks @Bjwebb 

Yes, that's much better!

Please fix / deploy when you see fit

**Comment by Bjwebb** [comment]
This should be fixed now.
